sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vijaymanda/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vijaymanda/react-test npm test

after_success:
  - docker build -t vijaymanda/multi-client ./client
  - docker build -t vijaymanda/multi-nginx ./nginx
  - docker build -t vijaymanda/multi-server ./server
  - docker build -t vijaymanda/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vijaymanda/multi-client
  - docker push vijaymanda/multi-nginx
  - docker push vijaymanda/multi-server
  - docker push vijaymanda/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-multi-aws"
  env: "Dockermultiaws-env"
  bucket_name: "elasticbeanstalk-us-east-2-933390069466"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
